
volumes:
  caddy_data:
  caddy_config:

name: pbblr-ozone
services:
  caddy:
    image: caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    depends_on:
      ozone:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /ozone/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=$CF_TUNNEL_TOKEN
    
  ozone:
    container_name: ozone
    image: ghcr.io/bluesky-social/ozone:0.1
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/xrpc/_health || exit 1
      interval: 4s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - /ozone/ozone.env

  postgres:
    container_name: postgres
    image: postgres:14.11-bookworm
    command: postgres -c listen_addresses=localhost
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - type: bind
        source: /ozone/postgres
        target: /var/lib/postgresql/data
    env_file:
      - /ozone/postgres.env

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: '@midnight'
      WATCHTOWER_LABEL_ENABLE: true
